<?php
use app\models\AlumniPublication;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
$this->title='Detail Alumni';
$photo=$model->photo?Yii::$app->request->baseUrl.'/'.ltrim($model->photo,'/'):null;
?>
<div class="row"><div class="col-md-8">
<div class="box box-success"><div class="box-body"><div style="display:flex;gap:18px;align-items:center"><?php if($photo): ?><img src="<?= Html::encode($photo) ?>" style="width:88px;height:88px;border-radius:18px;object-fit:cover"><?php else: ?><div style="width:88px;height:88px;border-radius:18px;background:#e9f4ec;display:grid;place-items:center;font-size:28px;font-weight:800;color:#166b42"><?= Html::encode(mb_substr($model->nama_lengkap,0,1)) ?></div><?php endif; ?><div><h2 style="margin:0"><?= Html::encode($model->nama_lengkap) ?></h2><p style="margin:5px 0">Alumni Batch <?= (int)$model->batch_number ?> · <?= Html::encode($model->location_name ?: '-') ?></p><p class="text-muted" style="margin:0"><?= Html::encode($model->current_position ?: 'Belum ada jabatan') ?><?= $model->current_institution?' — '.Html::encode($model->current_institution):'' ?></p></div></div><hr><p><?= nl2br(Html::encode($model->bio ?: 'Belum ada bio.')) ?></p><a class="btn btn-default btn-sm" href="<?= Url::to(['update','id'=>$model->id]) ?>">Edit Profil</a><?php if($model->is_public&&$model->verification_status==='verified'): ?> <a class="btn btn-success btn-sm" target="_blank" href="<?= Url::to(['/alumni/view','slug'=>$model->slug]) ?>">Lihat Publik</a><?php endif; ?></div></div>

<div class="box" id="karier"><div class="box-header with-border"><h3 class="box-title">Riwayat Karier</h3></div><div class="box-body">
<?php if(!$model->careers): ?><p class="text-muted">Belum ada riwayat karier.</p><?php endif; ?>
<?php foreach($model->careers as $c): ?><div style="padding:10px 0;border-bottom:1px solid #eee"><b><?= Html::encode($c->position_title) ?></b> — <?= Html::encode($c->institution_name) ?> <?= $c->is_current?'<span class="label label-success">Saat ini</span>':'' ?><br><small><?= Html::encode($c->sector ?: '-') ?> · <?= Html::encode($c->city ?: '-') ?> · <?= Html::encode($c->start_year ?: '?') ?>–<?= Html::encode($c->is_current?'Sekarang':($c->end_year?:'?')) ?></small> <?= Html::beginForm(['delete-career','id'=>$model->id,'careerId'=>$c->id],'post',['style'=>'display:inline','onsubmit'=>"return confirm('Hapus riwayat karier?')"]) ?><button class="btn btn-link btn-xs text-danger">Hapus</button><?= Html::endForm() ?></div><?php endforeach; ?>
<hr><?php $form=ActiveForm::begin(['action'=>['add-career','id'=>$model->id]]); ?><div class="row"><div class="col-md-6"><?= $form->field($career,'position_title')->textInput()->label('Jabatan') ?></div><div class="col-md-6"><?= $form->field($career,'institution_name')->textInput()->label('Instansi / Perusahaan') ?></div><div class="col-md-4"><?= $form->field($career,'sector')->textInput()->label('Sektor') ?></div><div class="col-md-4"><?= $form->field($career,'city')->textInput()->label('Kota') ?></div><div class="col-md-2"><?= $form->field($career,'start_year')->input('number')->label('Mulai') ?></div><div class="col-md-2"><?= $form->field($career,'end_year')->input('number')->label('Selesai') ?></div></div><?= $form->field($career,'is_current')->checkbox()->label('Pekerjaan saat ini') ?><button class="btn btn-primary btn-sm">Tambah Karier</button><?php ActiveForm::end(); ?>
</div></div>

<div class="box" id="karya"><div class="box-header with-border"><h3 class="box-title">Karya, Skripsi & Penelitian</h3></div><div class="box-body">
<?php if(!$model->allPublications): ?><p class="text-muted">Belum ada karya yang dicatat.</p><?php endif; ?>
<?php foreach($model->allPublications as $p): ?><div style="padding:10px 0;border-bottom:1px solid #eee"><b><?= Html::encode($p->title) ?></b> <span class="label label-info"><?= Html::encode(AlumniPublication::TYPES[$p->publication_type]??$p->publication_type) ?></span><?= $p->is_about_service?' <span class="label label-success">Tentang Pengabdian</span>':'' ?><br><small><?= Html::encode($p->publication_year ?: '-') ?> · <?= Html::encode($p->institution_or_publisher ?: '-') ?></small><?php if($p->url): ?> · <a target="_blank" href="<?= Html::encode($p->url) ?>">Buka tautan</a><?php endif; ?> <?= Html::beginForm(['delete-publication','id'=>$model->id,'publicationId'=>$p->id],'post',['style'=>'display:inline','onsubmit'=>"return confirm('Hapus karya ini?')"]) ?><button class="btn btn-link btn-xs text-danger">Hapus</button><?= Html::endForm() ?></div><?php endforeach; ?>
<hr><?php $form=ActiveForm::begin(['action'=>['add-publication','id'=>$model->id]]); ?><div class="row"><div class="col-md-7"><?= $form->field($publication,'title')->textInput()->label('Judul Karya') ?></div><div class="col-md-3"><?= $form->field($publication,'publication_type')->dropDownList(AlumniPublication::TYPES,['prompt'=>'Pilih jenis'])->label('Jenis') ?></div><div class="col-md-2"><?= $form->field($publication,'publication_year')->input('number')->label('Tahun') ?></div></div><div class="row"><div class="col-md-6"><?= $form->field($publication,'institution_or_publisher')->textInput()->label('Kampus / Penerbit') ?></div><div class="col-md-6"><?= $form->field($publication,'url')->textInput()->label('Tautan Repository / Publikasi') ?></div></div><?= $form->field($publication,'summary')->textarea(['rows'=>3])->label('Ringkasan') ?><div class="row"><div class="col-md-6"><?= $form->field($publication,'is_about_service')->checkbox()->label('Karya membahas pengalaman/pengabdian Sumut Mengajar') ?></div><div class="col-md-6"><?= $form->field($publication,'is_public')->checkbox()->label('Tampilkan di website') ?></div></div><button class="btn btn-primary btn-sm">Tambah Karya</button><?php ActiveForm::end(); ?>
</div></div>
</div>
<div class="col-md-4">
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Verifikasi & Publikasi</h3></div><div class="box-body"><?= Html::beginForm(['verify','id'=>$model->id],'post') ?><div class="form-group"><label>Status Verifikasi</label><?= Html::dropDownList('verification_status',$model->verification_status,['pending'=>'Menunggu Verifikasi','verified'=>'Terverifikasi','rejected'=>'Ditolak'],['class'=>'form-control']) ?></div><div class="checkbox"><label><?= Html::checkbox('is_public',(bool)$model->is_public,['value'=>1]) ?> Tampilkan profil di website</label></div><div class="checkbox"><label><?= Html::checkbox('is_featured',(bool)$model->is_featured,['value'=>1]) ?> Jadikan alumni unggulan</label></div><p class="help-block">Profil hanya boleh dipublikasikan jika persetujuan alumni sudah tercatat.</p><button class="btn btn-success btn-block">Simpan Status</button><?= Html::endForm() ?></div></div>
<div class="box"><div class="box-header with-border"><h3 class="box-title">Data Kontak</h3></div><div class="box-body"><dl><dt>WhatsApp</dt><dd><?= Html::encode($model->whatsapp) ?></dd><dt>Instagram</dt><dd><?= Html::encode($model->instagram ?: '-') ?></dd><dt>LinkedIn</dt><dd><?= Html::encode($model->linkedin ?: '-') ?></dd><dt>Persetujuan Publik</dt><dd><?= $model->consent_public?'Sudah tercatat':'Belum tercatat' ?></dd></dl></div></div>
</div></div>
