<?php
use app\models\AlumniPublication;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title=$model->nama_lengkap.' — Alumni Sumut Mengajar';
$photo=$model->photo?Yii::$app->request->baseUrl.'/'.ltrim($model->photo,'/'):null;
?>
<section class="alumni-profile-hero"><div class="container alumni-profile-grid"><div class="alumni-profile-photo"><?php if($photo): ?><img src="<?= Html::encode($photo) ?>" alt="<?= Html::encode($model->nama_lengkap) ?>"><?php else: ?><span><?= Html::encode(mb_strtoupper(mb_substr($model->nama_lengkap,0,1))) ?></span><?php endif; ?></div><div><a class="alumni-back" href="<?= Url::to(['/alumni/index']) ?>">← Kembali ke Alumni</a><span class="section-kicker">ALUMNI BATCH <?= (int)$model->batch_number ?></span><h1><?= Html::encode($model->nama_lengkap) ?></h1><p class="alumni-profile-lead"><?= Html::encode($model->current_position ?: 'Alumni Sumut Mengajar') ?><?= $model->current_institution?' di '.Html::encode($model->current_institution):'' ?></p><div class="alumni-meta"><span>📍 Pengabdian: <?= Html::encode($model->location_name ?: 'Sumatera Utara') ?></span><?php if($model->batch_year): ?><span>🗓 <?= (int)$model->batch_year ?></span><?php endif; ?><?php if($model->sector): ?><span>💼 <?= Html::encode($model->sector) ?></span><?php endif; ?></div></div></div></section>
<section class="section"><div class="container alumni-detail-layout"><div class="alumni-detail-main">
<div class="alumni-detail-card"><span class="section-kicker">CERITA ALUMNI</span><h2>Perjalanan setelah pengabdian.</h2><p><?= nl2br(Html::encode($model->bio ?: 'Profil ini sedang dilengkapi oleh tim Sumut Mengajar.')) ?></p></div>
<div class="alumni-detail-card"><span class="section-kicker">KARIER</span><h2>Jejak profesional.</h2><?php if(!$model->careers): ?><p class="alumni-muted">Riwayat karier belum dipublikasikan.</p><?php endif; ?><div class="career-timeline"><?php foreach($model->careers as $c): if(!$c->is_public)continue; ?><div class="career-item"><span><?= Html::encode($c->start_year ?: '') ?><?= $c->is_current?' — Sekarang':($c->end_year?' — '.Html::encode($c->end_year):'') ?></span><h3><?= Html::encode($c->position_title) ?></h3><p><?= Html::encode($c->institution_name) ?><?= $c->city?' · '.Html::encode($c->city):'' ?></p></div><?php endforeach; ?></div></div>
<div class="alumni-detail-card"><span class="section-kicker">KARYA & RISET</span><h2>Karya yang ditinggalkan.</h2><?php if(!$model->publications): ?><p class="alumni-muted">Belum ada karya yang dipublikasikan.</p><?php endif; ?><div class="publication-list"><?php foreach($model->publications as $p): ?><article><div><span class="publication-type"><?= Html::encode(AlumniPublication::TYPES[$p->publication_type]??$p->publication_type) ?></span><?= $p->is_about_service?'<span class="publication-service">Riset tentang Pengabdian</span>':'' ?></div><h3><?= Html::encode($p->title) ?></h3><p><?= Html::encode($p->institution_or_publisher ?: '') ?><?= $p->publication_year?' · '.(int)$p->publication_year:'' ?></p><?php if($p->summary): ?><div class="publication-summary"><?= nl2br(Html::encode($p->summary)) ?></div><?php endif; ?><?php if($p->url): ?><a class="text-link" target="_blank" rel="noopener" href="<?= Html::encode($p->url) ?>">Baca / lihat karya →</a><?php endif; ?></article><?php endforeach; ?></div></div>
</div><aside class="alumni-detail-side"><div class="alumni-side-card"><h3>Profil Singkat</h3><dl><dt>Batch</dt><dd><?= (int)$model->batch_number ?></dd><dt>Lokasi Pengabdian</dt><dd><?= Html::encode($model->location_name ?: '-') ?></dd><dt>Jabatan Saat Ini</dt><dd><?= Html::encode($model->current_position ?: '-') ?></dd><dt>Instansi</dt><dd><?= Html::encode($model->current_institution ?: '-') ?></dd><dt>Kota Bekerja</dt><dd><?= Html::encode($model->work_city ?: '-') ?></dd></dl></div><?php if($model->instagram||$model->linkedin): ?><div class="alumni-side-card"><h3>Terhubung</h3><?php if($model->linkedin): ?><a target="_blank" rel="noopener" href="<?= Html::encode($model->linkedin) ?>">LinkedIn →</a><?php endif; ?><?php if($model->instagram): ?><span>Instagram: <?= Html::encode($model->instagram) ?></span><?php endif; ?></div><?php endif; ?></aside></div></section>
